baseURL = 'https://zhongtao6.github.io/'
languageCode = 'en-us'
title = "Raw Thought"
theme = 'hugo-book'

[caches]
[caches.images]
dir = ':cacheDir/images'

[markup.goldmark.renderer]
  unsafe = true